version: '3.8'
services:
  web:
    container_name: php-app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./scripts:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - database

  database:
    container_name: php-db
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    hostname: database
    env_file: .env
volumes:
  postgres:
