version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web
    env_file: .env
    volumes:
      - ./scripts:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    ports:
      - '5432:5432'
    hostname: database
    env_file: .env
